### ISSUE TITLE
Strange theme for Windows VS Code

### ISSUE THREAD

**Issue by dmxt** [Entomy/Offbase-theme#1]
I only came on here because of the contribution request.

I don't know if it's like that for you guys on OS X - but here's what it looks like on Windows 10. The 1px border popping out is the worst.

![image](https://user-images.githubusercontent.com/3248782/65372480-de77ff80-dc3e-11e9-9764-acaaf635157f.png)

I liked the concept and was hoping for a good potential from somebody who has done study and is making a theme, but for now, I have to pass and maybe try again later.

**Comment by Entomy** [comment]
Hi, do you mean the 1 pixel dividing lines between panels?
I'm on Windows too actually, so I see the same UI.

**Comment by dmxt** [comment]
@Entomy Yup, I haven't seen those in most themes, I always found these too distractive.

There are few more things that are completely subjective like the palette choice for the JSON file (I didn't test on other files). Here's the comparison with the standard One Dark, where for my eyes, the color combination is more pleasant to look at and easier to read.
![Code_ee9F5BCBsC](https://user-images.githubusercontent.com/3248782/65372589-4844d900-dc40-11e9-99fd-56409b3357b7.png)

**Comment by dmxt** [comment]
I also want to chime in that the WSL or SSH connection corner button isn't distinctive. Have you used WSL before? It's very important to recognize which editor you're working on, hence the importance for the distinctiveness.

![chrome_KsJ74e8i4Z](https://user-images.githubusercontent.com/3248782/65372624-9ce85400-dc40-11e9-9188-571eb770a2d2.png)

**Comment by Entomy** [comment]
This theme was created before the SSH/WSL support, and I haven't had the time to update it for the new UI components, so that's why you're seeing that.

**Comment by Entomy** [comment]
![image](https://user-images.githubusercontent.com/25399505/65372674-1aac5f80-dc41-11e9-80f1-2828b0bf123f.png)

Here's a snippet of code with One Dark theming. The eye is generally drawn in a positive way towards green and yellow, as these are naturally extremely common colors, and drawn, but negatively, towards red as we've been taught this is an "alert" color that deserves attention. This means that the eye will be drawn overwhelmingly to the documentation comments and types of the method, only to then work towards more significant things like what the method actually is, or the internal code. A sizable chunk of the actual method body is completely unhighlighted, specifically part of the return expression. With very large expressions this can make readability quite hampered.

![image](https://user-images.githubusercontent.com/25399505/65372740-cd7cbd80-dc41-11e9-8453-abcbaae83e67.png)

This however is the same snippet with Offbase theming. The documentation tags are much less saturated, expression operators are highlighted, keywords have highlighting that is adjusted based on what they actually are, with some common traits, and so on.

**Comment by Entomy** [comment]
I'm sorry you feel these choices are "completely subjective", but they weren't. This is a preview release (notice the version number 0.28.0 has a major version number of 0), and still has kinks being worked out.

I've noted the 1px border because I agree with you, and subtler options like different panel background colors or drop shadows (if possible) would be better. But I also have to work with the features I'm given access too.

"the palette choice for the JSON file". Palette choice isn't (generally) language specific and I certainly didn't define my theme that way. Although I see there are considerable problems with JSON highlighting that need to be fixed. This is more of an issue with incomplete theming that anything else. I'll make a note of the problems I can see in your screenshot. Consider filing bug reports for further instances where coloring seems incorrect, such as running across multiple lexical units.

**Comment by Entomy** [comment]
I have to correct what I said. Unfortunantly I haven't finished my first cup of coffee for today yet, and forgot the snippet you attached was of your preferred One Dark theme, not my Offbase theme.

![image](https://user-images.githubusercontent.com/25399505/65372856-a45d2c80-dc43-11e9-89d0-3d6f5a5802dd.png)

While I see I could use highlighting of the property being defined, which would be a definate enhancement, I'm not quite sure why consistently highlightly values the same color is an issue.

You can see with your One Dark example, the same coloring is being used across `fontWeight: "normal"`, which actually seems incorrect on their end, as `fontWeight`, and its respective value are completely different lexical units with completely different semantic meaning. Consistency with this is then violated by the various properties with numerical values, which have the number a different color (good), but then the `fontFamily` declaration which absolutely bizarrely has the property name `fontFamily` highlighted as if it's a number (which it most definately is not).

**Comment by dmxt** [comment]
@Entomy I agree that the theme I'm using got highlighting wrong. It's not my preferred theme; it's just "one of that theme I'm okay with just for today, and I'll most likely change it all over again after a day."

Also, I don't know if you got your monitor calibrated[1], but I did, and I noticed that way too many VSCode themes completely fail at [WCAG AA or AAA standards](https://www.w3.org/TR/WCAG20/#visual-audio-contrast) with their contrast level and color combinations. I didn't test your theme with the visual calculator; I only can tell visually that the contrast is probably a bit too low for the standard; the same goes for color combination. Those themes are challenging to work on, especially for a prolonged time.

Post-calibrated monitors are very pleasant to look at except custom themes, custom themes are mostly my issues even my eyes are fine, I don't have color blindness, I don't need glasses to read microscopic text, it's just the color combination and low contrast certainly can make me feel uncomfortable after prolonged amount of time and I'm very thankful that only a few months ago people really started taking these visual standards seriously.

[1] Everybody has to calibrate their monitor with the hardware calibrator no matter how fancy the piece of calibration paper that came with monitors each time they order it

**Comment by Entomy** [comment]
Contrast ratio for unhighlighted text is 9.9:1, by far exceeding the recommended "enhanced" contrast of 7:1.

Contrast ratio for highlighted text is far more complicated, because humans are more complex than a ratio of luminance between the most white and the most black a display will produce; human vision is far more complex; and we're not designing themes for the monitor, we're designing the theme for the human. For demonstration, which contrast is most eye catching? Not calculated, just what your eyes tell you.

![image](https://user-images.githubusercontent.com/25399505/65373229-bab9b700-dc48-11e9-9742-6bcf561e28ae.png)

![image](https://user-images.githubusercontent.com/25399505/65373202-539c0280-dc48-11e9-85b1-a24eb8cc727e.png)

![image](https://user-images.githubusercontent.com/25399505/65373206-5dbe0100-dc48-11e9-9103-dba6f351d39d.png)

> "I noticed that way too many VSCode themes completely fail at WCAG AA or AAA standards with their contrast level and color combinations. I didn't test your theme with the visual calculator"

> ***"I didn't test your theme with the visual calculator"***

If there's an issue with my theme specifically, please point that out. However, please do not criticize my theme for the failings of others, especially having not testing my theme for failing those. This is the same kind of thinking responsible for things like racism. I am not guilty for the failings of other themes.

**Comment by dmxt** [comment]
My least favorite color on the background is blue, and it's not in your list. Then right next to the blue, there's super bright white which is pretty distractive due to an extreme contrast imbalance between super-low contrasted blue and super high contrasting white. I'm not a fan of the color choice for brown, but this is subjective, I feel that chocolate brown is a pleasant type but green-brownish isn't.

I only posted because you specifically requested us to try to "help out" by responding about what I thought of the theme and give reasons why I uninstalled it. I did not expect you to take all of this personally and start comparing it to racism, because of this, it's best to stop and close this thread now.

**Comment by Entomy** [comment]
Furthermore, this is from [your own website](http://dmxt.org/works/aurello)

![Annotation 2019-09-21 083059](https://user-images.githubusercontent.com/25399505/65373347-644d7800-dc4a-11e9-845d-69169e0cb9a3.png)

With a contrast ratio of 1.63:1, failing to come even close to WCAG AA standards, and being visually difficult to read.

Yet another one from [your own website](http://dmxt.org/works/alerttheboss)

![Annotation 2019-09-21 083625](https://user-images.githubusercontent.com/25399505/65373410-2a30a600-dc4b-11e9-9c22-3122ef6938aa.png)

With a contrast ratio of 1.99:1, failing to come even close to WCAG AA standards, and being visually difficult to read.

So I also fail to understand why I'm being criticized for an unverified (as you said) issue you think I have, that your own works suffer from terribly.
